### ISSUE TITLE
Inline call errors if value propagation encounters unknown operators

### ISSUE THREAD

**Issue by JoelHuberQC** [Quantco/spox#103]
## Description
When passing a model to inline which contains an unknown operator, the onnx reference value propagation backend returns an empty dictionary (see _value_prop:160). However, this makes inline error out, since inline expects to receive values from the value propagation backend. In particular, the error we get is some random KeyError when it is trying to extract the values.

I would expect that in this case, value propagation just silently fails, without crashing the code.

## How to Reproduce:
```python
import numpy as np
from onnx import helper
from onnx.checker import check_model
from onnxruntime import InferenceSession
from spox import inline
from spox.opset.ai.onnx import v18 as op

model_input = [helper.make_tensor_value_info("X", elem_type=8, shape=("X",))]
model_output = [
    helper.make_tensor_value_info("y", elem_type=8, shape=("y", "max_words"))
]

# Take the tokenizer from the microsoft contrib domain for example
nodes = [
    helper.make_node(
        "Tokenizer",
        inputs=["X"],
        outputs=["y"],
        domain="com.microsoft",
        mincharnum=1,
        mark=0,
        pad_value="",
        separators=[" "],
    )
]

graph = helper.make_graph(
    nodes,
    "Tokenizer",
    model_input,
    model_output,
)

model = helper.make_model(
    graph,
    opset_imports=[
        helper.make_opsetid("", 18),
        helper.make_opsetid("com.microsoft", 1),
    ],
)

# Model is valid and works on onnxruntime
check_model(model, full_check=True)
ort_output = InferenceSession(model.SerializeToString()).run(
    None, {"X": np.array(["Test Test"])}
)
print(ort_output)

# This crashes since the value prop backend doesn't give an output
spox_const_res = inline(model)(X=op.const(["Test Test"], dtype=np.str_))
```

## Expected Behaviour
Code works, no error, but no value propagation is performed.

## Actual Behaviour
The script throws an error:
```
Traceback (most recent call last):
 [...]
  File "/path/to/spox/_inline.py", line 138, in propagate_values
    return {
  File "/path/to/spox/_inline.py", line 139, in <dictcomp>
    f"outputs_{k}": unwrap_feed(var.unwrap_type(), output_feed[o.name]).value
KeyError: 'y'
```

**Comment by jbachurski** [comment]
Hey! Thanks for reporting the bug. It shouldn’t be too difficult to fix, there just are some inconsistencies in how errors in the runtime are handled during value propagation. In this particular case [NotImplementedError is ignored](https://github.com/Quantco/spox/blob/4ecf0f75ab8f96b8a49e2f99812b219dfcb4850e/src/spox/_value_prop.py#L159) for the reference runtime. I must have forgotten about this and handled this code path wrong.
I don’t really have a possibility of looking into this right now, but you can try submitting a PR if you like and adding a test. I would suspect the ORT backend would have a similar issue for custom operators. On that subject, for this ORT operator as a workaround you should be able to [change the backend](https://spox.readthedocs.io/en/latest/manual/unstable.html#value-propagation-backend) - or you can try disabling value prop or removing the Var values to avoid it triggering.
