### ISSUE TITLE
Validate ONNX 1.15rc1

### ISSUE THREAD

**Issue by justinchuby** [Quantco/spox#111]
Hi! The release candidate for ONNX 1.15 is released at https://test.pypi.org/project/onnx/1.15.0rc1/. Please feel free to validate against it and report any issues. 

Release wiki: https://github.com/onnx/onnx/wiki/Logistics-for-ONNX-Release-1.15.0

**Comment by jbachurski** [comment]
Thanks for the heads up!
@cbourjau Maybe you could look into this to avoid breakage later on? I assume we also want to build the new opset in due time, too, to support your proposed operators.
We might want to consider a ONNX nightly CI if that would be possible to set up.

**Comment by cbourjau** [comment]
Yes, thanks for the heads up, @justinchuby ! I simply [installed](https://github.com/Quantco/spox/compare/cbourjau-patch-1...onnx-rc1) the RC in a hackish way in CI. I'm afraid there are indeed some [issues](https://github.com/Quantco/spox/actions/runs/6571828762/job/17851736118#step:4:52). At first sight, they appear to be related to subgraphs and/or updating nodes from older opsets. @adityagoel4512 , could you maybe take a closer look and file an issue upstream if warranted?

**Comment by justinchuby** [comment]
I think @liqunfu is targeting an official release this week. I would be create an ONNX issue for awareness if anything doesn’t work

**Comment by cbourjau** [comment]
Spox is now compatible with onnx 1.15rc1 as of the [0.9.3 release](https://github.com/Quantco/spox/releases/tag/0.9.3).
