### ISSUE TITLE
Inline sub-model cannot cope with superset inputs (more inputs than expected)

### ISSUE THREAD

**Issue by adityagoel4512** [Quantco/spox#171]
(as originally mentioned by @EmilyMohellenbrandQC).

https://github.com/Quantco/spox/blob/e88344b601d3dffd28de61af3bac96a05dc1a2a9/src/spox/_public.py#L292-L295

The current inline function checks if the supplied arguments `kwargs` are the exact same set as the inline model's expected inputs `in_names`. 

This could cause error if the supplied arguments are propagated down directly from the inputs of the main model, because the inputs to main model is likely to be a superset of the inputs to the sub-model.
e.g. If the main model is built with combining two inline sub-models 
```main_model = combine(inline(sub_model_a), inline(sub_model_b))```, 
where the `main_model` expects input `{"a", "b"}`, `sub_model_a` expects input `{"a"}` and `sub_model_b` expects input `{"b"}`. 
When the arguments `{"a", "b"}` are directly passed down to `sub_model_a`, this causes error.

A fix would be to check if `kwargs` is a superset of `in_names` instead of exact same set, i.e. 
`if not set(in_names).issubset(set(kwargs)):`

I tried the fix and it solves the issue.

**Comment by cbourjau** [comment]
I'm not sure this needs to be in Spox. `inline` creates a function from a ModelProto that has the kwargs of the inlined model and behaves exactly like any other opset function. As far as I'm aware there is no function in the opset that would just take `**kwargs` and silently ignore some of them. It also seems a bit odd with respect to the `inline`d function also accepting `*args`. It seems that you could just have a small wrapper on your side to accommodate your particular use case (untested):

```python
from spox import inline as _inline
from spox import Var

def inline(model_proto) -> Callable[..., dict[str, Var]]:
    names = [item.name for item in model_proto.graph.input]
    fn_strict = _inline(model_proto)
    def fn_kwargs_only(**kwargs: Var):
        """Kw-only function which ignores some unneeded inputs."""
        return fn_strict(**{k: v for k, v in kwargs.items() if k in names})
        
    return fn_kwargs_only
```

If it is helpful we may also consider giving the inlined function an explicit signature. This way you may use the `inspect` module to get a signature from the inline function. [Here](https://github.com/fastai/fastcore/blob/master/fastcore/meta.py#L95) is an example of how one may do that.

**Comment by EmilyMohellenbrandQC** [comment]
> I'm not sure this needs to be in Spox. `inline` creates a function from a ModelProto that has the kwargs of the inlined model and behaves exactly like any other opset function. As far as I'm aware there is no function in the opset that would just take `**kwargs` and silently ignore some of them. It also seems a bit odd with respect to the `inline`d function also accepting `*args`. It seems that you could just have a small wrapper on your side to accommodate your particular use case (untested):
> 
> ```python
> from spox import inline as _inline
> from spox import Var
> 
> def inline(model_proto) -> Callable[..., dict[str, Var]]:
>     names = [item.name for item in model_proto.graph.input]
>     fn_strict = _inline(model_proto)
>     def fn_kwargs_only(**kwargs: Var):
>         """Kw-only function which ignores some unneeded inputs."""
>         return fn_strict(**{k: v for k, v in kwargs.items() if k in names})
>         
>     return fn_kwargs_only
> ```
> 
> If it is helpful we may also consider giving the inlined function an explicit signature. This way you may use the `inspect` module to get a signature from the inline function. [Here](https://github.com/fastai/fastcore/blob/master/fastcore/meta.py#L95) is an example of how one may do that.

Thank you for your suggestion. I tried your solution and it works. 

However, I would still argue that inline models should allow more than expected inputs. The `inline` function is meant to assist building a bigger model from smaller models. And the scenario where the big model propagates all input arguments to its sub-models is not an unusual case. And the `inline` function should be convenient enough to handle this situation. 

If inline model can only accept its exact inputs, it's likely that downstream always need a similar custom wrapper. IMHO, this is unnecessary inconvenience just because we want to keep `inline` behaving similar to other functions.

**Comment by EmilyMohellenbrandQC** [comment]
> This sounds reasonable to me on first glance. Would you be able to create a PR?

Yes, PR [here](https://github.com/Quantco/spox/pull/172)

**Comment by cbourjau** [comment]
I think your use case may be more specialized than you may think. I, for one, have not yet come across your particular issue, yet. Furthermore, one may also argue in the opposite direction: If the inlined model does not meet expectations for its API, it may very well indicate a bug. Maybe you thought the inlined model takes a `weights` argument into account, but something went wrong when building it, and it doesn't even have "weights" in its signature. In such a case a developer would certainly appreciate an error being raised. Quietly ignoring unused kwargs seems quite opinionated IMHO and, at the same time, easy to work around downstream in a way that suits every individual use case.

**Comment by EmilyMohellenbrandQC** [comment]
Alright, your argument is also reasonable. I'll close this issue and PR.

**Comment by EmilyMohellenbrandQC** [comment]
Decided to keep the current behavior of `inline` and accommodate the special cases by custom wrappers in downsream.
