### ISSUE TITLE
Should spox.opset.ai.onnx.vXX.const default to float64 for float input?

### ISSUE THREAD

**Issue by cbourjau** [Quantco/spox#24]
Numpy defaults to float64 when presented with python `float`s:
```
np.array([3.14]).dtype == np.dtype("float64")
```

However, the `const` convenience method defaults to `float32`. We should consider changing this behavior in order to stay closer to numpy's behavior.

**Comment by JakubBachurskiQC** [comment]
I'm debating whether we should be using `Constant` for this at all. It seems that initialisers are the actual expected mechanism for constants on this IR version. We'll get to this issue if we want to do #25 - as other opset modules (well, only `ai.onnx.ml` currently) will also want to construct constants. So maybe the actual best approach is to expose a `spox.const|initializer` `(ArrayLike) -> Var` public function that uses initialisers underneath?
