### ISSUE TITLE
Add typing_extensions dependency explicitly or remove it

### ISSUE THREAD

**Issue by cbourjau** [Quantco/spox#70]
Things work right now because `onnx` also depends on it but we should make it explicit. See also: https://github.com/conda-forge/spox-feedstock/pull/3#issue-1646329317

**Comment by JakubBachurskiQC** [comment]
I'd be fine dropping the dependency entirely, as it seems to only be used in an internal which isn't even in `_future`. 

Only use (?):

https://github.com/Quantco/spox/blob/0ca5281cfd3e5dc4fabc7b815cac2dff877128d0/src/spox/_function.py#L1-L24
https://github.com/Quantco/spox/blob/0ca5281cfd3e5dc4fabc7b815cac2dff877128d0/src/spox/_function.py#L150-L166
