### ISSUE TITLE
Patch shape inference for If

### ISSUE THREAD

**Issue by cbourjau** [Quantco/spox#77]
Currently, using `If` drops the shapes of the outputs if broadcasting is needed to compute the correct shape of the two outputs. While properly implementing broadcasting with dim-variables is tricky, we can do a better if one of the branches is a scalar (e.g. a fill value). In that case, we know that the output shape will always be the one of the non-scalar branch.

**Comment by jbachurski** [comment]
Behaviour seems to be as expected. If the shapes are of different ranks there's no way of writing a common, 'compatible' shape like the [standard](https://github.com/onnx/onnx/blob/main/docs/Operators.md#If) attempts to describe. Hence no shape is assigned, as the rank is unknown.
I think the best solution is to Squeeze/Expand explicitly into the target shape (rank), or bite the bullet that the shape is unknown for the output (as the rank is indeed unknown, even if we can guarantee the value could broadcast into that rank).

**Comment by cbourjau** [comment]
Oh, I see! Thanks!
